# Generated by Django 3.1.2 on 2021-10-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NickName', default=None, max_length=5000, null=True)),
                ('wallet_address', models.CharField(db_column='Wallet', max_length=5000)),
                ('firma', models.CharField(db_column='Firma', max_length=5000)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserWallet',
            },
        ),
    ]
