# Generated by Django 3.1.2 on 2021-10-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoapLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_poap', models.CharField(db_column='LinkPoap', default=None, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'PoapLink',
            },
        ),
    ]
